@COPY /Y "MakeMesh\CPU\MakeMesh.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "MakeFace\CPU\MakeFace.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "MakeQuad\CPU\MakeQuad.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "Electrify\CPU\Electrify.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "MakeRHS\CPU\MakeRHS.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "MakeMoM\CPU\MakeMoM.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "SolveMoM\CPU\SolveMoM.exe" "..\MATLAB\TEST\Applet\"
@COPY /Y "ObserveRCS\CPU\ObserveRCS.exe" "..\MATLAB\TEST\Applet\"